### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by laixintao**
markdown syntax fix

### CODE REVIEW

**Comment by MylesBorins** [comment]
A++ thanks. How did you find this repo?

**Comment by laixintao** [comment]
@MylesBorins You are welcome, @kennethreitz started this repo, I'm ... an obsessive person.

**Comment by MylesBorins** [comment]
that is hilarious. I was showing him it tonight and complained about how github changed their markdown renderer and how it was broken

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by MylesBorins** [comment]
@kennethreitz ZERO INBOX'd

**Pull request merged**
